name: "regolith"
description: "Bedrock Addons compiler pipeline."
inputs:
  profile:
    description: "profile to run"
    default: "default"
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/bedrock-oss/regolith-action:latest'
  args:
    - ${{ inputs.profile }}