name: "regolith"
description: "Bedrock Addons compiler pipeline."
inputs:
  profile:
    description: "profile to run"
    default: "default"
    required: false

runs:
  using: 'composite'
  steps:
    - name: deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
    - name: nim
      uses: iffy/install-nim@v4.2.0
      with:
        version: stable
    - name: regolith
      run: |
        version=`cat /version`
        wget https://github.com/Bedrock-OSS/regolith/releases/download/$(cat version)/regolith_$(cat version)_Linux_x86_64.tar.gz
        tar -xzf regolith_$(cat version)_Linux_x86_64.tar.gz
        mv regolith /usr/local/bin
        rm regolith_$(cat version)_Linux_x86_64.tar.gz
        chmod +x /usr/local/bin/regolith
    - name: unlock
      run: regolith unlock
    - name: install
      run: regolith install-all
    - name: list versions
      run: |
        python --version
        node -v
        nim -v
        java -version
        deno --version
        dotnet --list-sdks
    - name: compile
      run: regolith run ${{inputs.profile}}