name: "regolith"
description: "Bedrock Addons compiler pipeline."
inputs:
  profile:
    description: "profile to run"
    default: "default"
    required: false
  github_token:
    description: "GitHub Token for getting private filters"
    default: ""
    required: false
  github_username:
    description: "GitHub username for getting private filters"
    default: ""
    required: false

runs:
  using: 'composite'
  steps:
    - name: setup-git-credentials
      uses: de-vri-es/setup-git-credentials@v2.0.8
      if: ${{ inputs.github_token != '' }}
      with:
        credentials: https://${{ inputs.github_username }}:${{ inputs.github_token }}@github.com/
    - name: deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
    - name: nim
      uses: iffy/install-nim@v4.2.0
      with:
        version: stable
    - name: list versions
      shell: bash
      run: |
        python --version
        node -v
        nim -v
        java -version
        deno --version
        dotnet --list-sdks
    - name: regolith
      shell: bash
      run: |
        wget https://github.com/Bedrock-OSS/regolith/releases/download/$(cat ${{ github.action_path }}/version)/regolith_$(cat ${{ github.action_path }}/version)_Linux_x86_64.tar.gz
        tar -xzf regolith_$(cat ${{ github.action_path }}/version)_Linux_x86_64.tar.gz
        mv regolith /usr/local/bin
        rm regolith_$(cat ${{ github.action_path }}/version)_Linux_x86_64.tar.gz
        chmod +x /usr/local/bin/regolith
    - name: unlock
      shell: bash
      run: sudo regolith unlock
    - name: install
      shell: bash
      run: sudo regolith install-all
    - name: compile
      shell: bash
      run: sudo regolith run ${{inputs.profile}}